import Head from 'next/head'
import Image from 'next/image'
import Footer from '@/components/Footer'
import styles from '@/styles/Home.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>Assignment 1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
      <div className={styles.main_container}>

            <div className={styles.leftarea}>
                    <img className={styles.xImg} src="/images/twitter_logo.png" />
            </div>

            <div className={styles.rightarea}>
                <h2 className={styles.h2}>Happening now</h2>
                <h3 className={styles.h3}>Join today.</h3>

                <div className={styles.signin_google}>
                    <img className={styles.google_logo} src="/images/google_logo.jpeg" height="35px"/>
                    <p className={styles.sg_1}>Sign in with Google</p>
                    <div clasName={styles.goolge_icon}></div>
                </div>

                <div className={styles.signin_apple}>
                    <div className={styles.apple_icon}></div>
                    <img src="/images/apple_logo.jpeg" height="35px"/>
                    <p className={styles.sa_1}>Sign in with Apple</p>
                </div>

                <div className={styles.br_line}>
                  <div className={styles.f_line}></div>
                  <div className={styles.or_line}>or</div>
                  <div className={styles.f_line}></div>
                </div>

                <div className={styles.create_account}>
                    <p className={styles.ca}>Create account</p>
                </div>
                
                <div className={styles.policy}>
                    <p>By signing up, you agree to the <span className={styles.text_blue}>Terms of Service</span> and <span className={styles.text_blue}>Privacy Policy</span>, including <span className={styles.text_blue}>Cookie Use.</span></p>
                </div>

                <div className={styles.ea_line}>Already have an account?</div>
                  <div className={styles.signin_bt}>
                    <p className={styles.si}>Sign in</p>
                  </div>
            </div>
        </div>
      </main>
      <Footer/>
    </>
  )
}
